name: Add Reviewers

on:
  workflow_call:
    secrets:
      GA_TOKEN:
        required: true

jobs:
  add-reviewers:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GA_TOKEN }}
        reviewers: cluny85,mfhevia,ddoice
        re-request-when-approved: true
        re-request-when-changes-requested: true
