name: Reviewers

on:
  workflow_call:
    secrets:
      REPO_ADMIN_TOKEN:
        required: true
jobs:
  add-reviewers:
    name: Add reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: bagonboard/github-actions
          token: ${{ secrets.REPO_ADMIN_TOKEN }}
          path: .github-actions/
      - name: list 1
        run: ls -la .github
      - name: list 2
        run: ls -la .github-actions
      - name: cp
        run: cp .github-actions/.github/auto_assign.yml .github/auto_assign.yml
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/auto_assign.yml"