name: Install

on:
  workflow_call:
    secrets:
      NPM_TOKEN_READ:
        required: true
      GA_TOKEN:
        required: false
    inputs:
      USE_YARN:
        required: false
        type: boolean
        default: false
      WORKING_DIRECTORY:
        required: false
        type: string
        default: .
      FORCE_INSTALL:
        required: false
        type: string

jobs:
  install:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:     

    - uses: actions/checkout@v2

    - name: Check package-lock file exists
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      if: ${{ inputs.USE_YARN == false }}
      run: |
        if [ ! -f package-lock.json ]
        then
          echo ⚠️ package-lock.json file not found
          ls -la
          exit 2
        fi
        
    - name: Check yarn.lock file exists
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      if: ${{ inputs.USE_YARN == true }}
      run: |
        if [ ! -f yarn.lock ]
        then
          echo ⚠️ yarn.lock file not found
          ls -la
          exit 2
        fi

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles( inputs.USE_YARN && 'yarn.lock' || 'package-lock.json' ) }}

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Echo versions
      run: |
        node -v
        npm -v

    - name: Create npmrc
      run: |
        if [ ! -z "$GA_TOKEN" ]
        then
          echo "//npm.pkg.github.com/:_authToken=$GA_TOKEN" > ~/.npmrc
          echo "@bagonboard:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo ~/.npmrc created ✔️
        else
          echo ~/.npmrc NOT created 🚨
        fi
      env:
        GA_TOKEN: ${{ secrets.GA_TOKEN }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.FORCE_INSTALL != ''
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        echo USE_YARN:$USE_YARN
        if [ -z "$USE_YARN" ]
        then
          npm ci
        else
          yarn install
        fi      
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
        GA_TOKEN: ${{ secrets.GA_TOKEN }}
