name: Install

on:
  workflow_call:
    secrets:
      NPM_TOKEN_READ:
        required: true
      GA_TOKEN:
        required: false
    inputs:
      WORKING_DIRECTORY:
        required: false
        type: string
        default: .

jobs:
  install:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:     

    - uses: actions/checkout@v2

    - name: Check package-lock file exists
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        if [ ! -f package-lock.json ]
        then
          echo ⚠️ package-lock.json file not found
          ls -la
          exit 2
        fi

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: npm --verbose ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
        GA_TOKEN: ${{ secrets.GA_TOKEN }}