name: Install

on:
  workflow_call:
    secrets:
      NPM_TOKEN_READ:
        required: true

jobs:
  install:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:     

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12.16.1'
        registry-url: 'https://registry.npmjs.org'

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci || npm i
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_READ }}        