name: Install

on:
  workflow_call:
    secrets:
      NPM_TOKEN_READ:
        required: true
      GA_TOKEN:
        required: false
    inputs:
      NODE_VERSION:
        required: false
        type: string
        default: 14
      WORKING_DIRECTORY:
        required: false
        type: string
        default: .
      FORCE_INSTALL:
        required: false
        type: string

jobs:
  install:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Check yarn.lock file exists
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        if [ ! -f yarn.lock ]
        then
          echo ⚠️ yarn.lock file not found
          ls -la
          exit 2
        fi

    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          node_modules
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'

    - name: Echo versions
      run: |
        node -v
        yarn -v

    - name: Create npmrc
      run: |
        if [ ! -z "$GA_TOKEN" ]
        then
          echo "//npm.pkg.github.com/:_authToken=$GA_TOKEN" > ~/.npmrc
          echo "@bagonboard:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo ~/.npmrc created ✔️
        else
          echo ~/.npmrc NOT created 🚨
        fi
      env:
        GA_TOKEN: ${{ secrets.GA_TOKEN }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.FORCE_INSTALL != ''
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
        GA_TOKEN: ${{ secrets.GA_TOKEN }}
