name: Notify

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_CI:
        required: true
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      EMOJI:        
        type: string

jobs:
  slack:
    name: Notify in slack
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: come25136/workflow-notification-for-slack@main
        with:
          repo_token: ${{github.token}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_CI}}
          name: ${{ inputs.PROJECT_NAME }}
          icon_emoji: ${{ inputs.EMOJI }}
