name: Sonarqube
on:
  workflow_call:
    secrets:
      SONARQUBE_HOST:
        required: true
      SONARQUBE_TOKEN:
        required: true
    inputs:
      PROJECT_NAME:
        required: true
        type: string
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Cache lcov file
        uses: actions/cache@v2
        with:
          path: coverage/lcov.info        
          key: ${{ runner.os }}-${{ inputs.PROJECT_NAME }}-lcov-${{ github.run_number }}
      - name: Scan code
        uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ github.token }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          host: ${{ secrets.SONARQUBE_HOST }} # Variable set in the Github Secrets
          token: ${{ secrets.SONARQUBE_TOKEN }} # Variable set in the Github Secrets
      
      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
